### ISSUE TITLE
WCOSS2 with g2/3.5.1 and g2tmpl/1.13.0

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/WCOSS2-requests#4]
> Hi all,
> 
> Just wanted to check on the status of having g2tmpl/1.13.0 and g2/3.5.1 installed on WCOSS2?
> 
> Thank you,
> 
> Andrew
> 
> 
> On Mon, Jul 22, 2024 at 10:20 AM Wen Meng - NOAA Federal <[wen.meng@noaa.gov](mailto:wen.meng@noaa.gov)> wrote:
> Hang,
> 
> I conducted the UPP test and validated the expected changes. From my perspective, you may let NCO know g2tmpl/1.13.0 and g2/3.5.1 are ready for installation at /apps/ops/prod on WCOSS2.
> 
> Thanks,
> 
> Wen
> 
> On Mon, Jul 22, 2024 at 9:07 AM Hang Lei - NOAA Affiliate <[hang.lei@noaa.gov](mailto:hang.lei@noaa.gov)> wrote:
> Hi, Wen and Pan Li,
> 
> NCO has quickly installed the requested libraries. Please test them as:
> 
> hang.lei@clogin01:~> module use /apps/ops/para/libs/modulefiles/compiler/intel/19.1.3.304
> hang.lei@clogin01:~> module load g2/3.5.1
> hang.lei@clogin01:~> module show g2/3.5.1
> -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
>    /apps/ops/para/libs/modulefiles/compiler/intel/19.1.3.304/g2/3.5.1.lua:
> -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> help([[]])
> conflict("g2")
> setenv("g2_ROOT","/apps/ops/para/libs/intel/19.1.3.304/g2/3.5.1")
> setenv("g2_VERSION","3.5.1")
> setenv("G2_INC4","/apps/ops/para/libs/intel/19.1.3.304/g2/3.5.1/include_4")
> setenv("G2_INCd","/apps/ops/para/libs/intel/19.1.3.304/g2/3.5.1/include_d")
> setenv("G2_LIB4","/apps/ops/para/libs/intel/19.1.3.304/g2/3.5.1/lib64/libg2_4.a")
> setenv("G2_LIBd","/apps/ops/para/libs/intel/19.1.3.304/g2/3.5.1/lib64/libg2_d.a")
> whatis("Name: g2")
> whatis("Version: 3.5.1")
> whatis("Category: library")
> whatis("Description: g2 library")
> 
> hang.lei@clogin01:~> ls /apps/ops/para/libs/intel/19.1.3.304/g2/3.5.1/include_4
> drstemplates.mod  g2grids.mod  g2logging.mod  grib_mod.mod  gridtemplates.mod  intmath.mod  params_ecmwf.mod  params.mod  pdstemplates.mod  re_alloc.mod
> hang.lei@clogin01:~> module show w3emc/2.12.0
> -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
>    /apps/ops/para/libs/modulefiles/compiler/intel/19.1.3.304/w3emc/2.12.0.lua:
> -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> help([[]])
> conflict("w3emc")
> setenv("w3emc_ROOT","/apps/ops/para/libs/intel/19.1.3.304/w3emc/2.12.0")
> setenv("w3emc_VERSION","2.12.0")
> setenv("W3EMC_INC4","/apps/ops/para/libs/intel/19.1.3.304/w3emc/2.12.0/include_4")
> setenv("W3EMC_INC8","/apps/ops/para/libs/intel/19.1.3.304/w3emc/2.12.0/include_8")
> setenv("W3EMC_INCd","/apps/ops/para/libs/intel/19.1.3.304/w3emc/2.12.0/include_d")
> setenv("W3EMC_LIB4","/apps/ops/para/libs/intel/19.1.3.304/w3emc/2.12.0/lib64/libw3emc_4.a")
> setenv("W3EMC_LIB8","/apps/ops/para/libs/intel/19.1.3.304/w3emc/2.12.0/lib64/libw3emc_8.a")
> setenv("W3EMC_LIBd","/apps/ops/para/libs/intel/19.1.3.304/w3emc/2.12.0/lib64/libw3emc_d.a")
> whatis("Name: w3emc")
> whatis("Version: 2.12.0")
> whatis("Category: library")
> whatis("Description: w3emc library")
> 
> hang.lei@clogin01:~> ls /apps/ops/para/libs/intel/19.1.3.304/w3emc/2.12.0/include_4/
> mersenne_twister.mod
> hang.lei@clogin01:~> module show g2tmpl
> g2tmpl         g2tmpl/1.10.0  g2tmpl/1.10.2  g2tmpl/1.12.0  g2tmpl/1.13.0  g2tmpl/1.9.1  
> hang.lei@clogin01:~> module show g2tmpl
> g2tmpl         g2tmpl/1.10.0  g2tmpl/1.10.2  g2tmpl/1.12.0  g2tmpl/1.13.0  g2tmpl/1.9.1  
> hang.lei@clogin01:~> module show g2tmpl
> g2tmpl         g2tmpl/1.10.0  g2tmpl/1.10.2  g2tmpl/1.12.0  g2tmpl/1.13.0  g2tmpl/1.9.1  
> hang.lei@clogin01:~> module show g2tmpl/1.13.0
> -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
>    /apps/ops/para/libs/modulefiles/compiler/intel/19.1.3.304/g2tmpl/1.13.0.lua:
> -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> help([[]])
> conflict("g2tmpl")
> setenv("g2tmpl_ROOT","/apps/ops/para/libs/intel/19.1.3.304/g2tmpl/1.13.0")
> setenv("g2tmpl_VERSION","1.13.0")
> setenv("G2TMPL_INC","/apps/ops/para/libs/intel/19.1.3.304/g2tmpl/1.13.0/include")
> setenv("G2TMPL_LIB","/apps/ops/para/libs/intel/19.1.3.304/g2tmpl/1.13.0/lib64/libg2tmpl.a")
> whatis("Name: g2tmpl")
> whatis("Version: 1.13.0")
> whatis("Category: library")
> whatis("Description: g2tmpl library")
> 
> hang.lei@clogin01:~> ls /apps/ops/para/libs/intel/19.1.3.304/g2tmpl/1.13.0/include
> grib2_all_tables_module.mod
> 
> On Wed, Jul 17, 2024 at 3:09 PM Hang Lei - NOAA Affiliate <[hang.lei@noaa.gov](mailto:hang.lei@noaa.gov)> wrote:
> Okay, will prepare 
> Thanks 
> Hang
> 
> On Wed, Jul 17, 2024 at 3:08 PM Wen Meng - NOAA Federal <[wen.meng@noaa.gov](mailto:wen.meng@noaa.gov)> wrote:
> Thanks Li for testing g2 and g2tmpl installation on WCOSS2 with the UPP.
> 
> Hi Hang,
> 
> Could you send the code delivery form to NCO for library official installation on WCOSS2?
> 
> Thanks,
> 
> Wen
> 
> 
> 
> 
> 
> On Wed, Jul 17, 2024 at 2:44 PM Li Pan - NOAA Affiliate <[li.pan@noaa.gov](mailto:li.pan@noaa.gov)> wrote:
> Hang, 
> 
>   With the libraries you installed, everything works fine. 
> 
>   My tests can be found at /lfs/h2/emc/ens/save/li.pan/UPP . 
> 
>  The output is at /lfs/h2/emc/ptmp/li.pan/post_gefs_2013040100
> 
>  Cheers,
> 
> Li 
> 
> On Wed, Jul 17, 2024 at 10:04 AM Hang Lei - NOAA Affiliate <[hang.lei@noaa.gov](mailto:hang.lei@noaa.gov)> wrote:
> In addition, when testing g2/2.5.1, please also load w3emc, bacio, jasper, libpng, and jpeg.  
> W3emc and bacio are added as dependencies after version 3.4.5
> Before that, it is not required.
> 
> Thanks,
> Hang
> 
> On Wed, Jul 17, 2024 at 9:59 AM Hang Lei - NOAA Affiliate <[hang.lei@noaa.gov](mailto:hang.lei@noaa.gov)> wrote:
> hi, Pan Li,
> 
> I reinstall the g2 tag 3.5.1 on cactus, please double check if the package is the correct one.
> hang.lei@clogin03:/lfs/h2/emc/eib/save/hang.lei/forgdit/nco_wcoss2> module use /lfs/h2/emc/eib/save/hang.lei/forgdit/nco_wcoss2/install2/modulefiles/compiler/intel/19.1.3.304
> hang.lei@clogin03:/lfs/h2/emc/eib/save/hang.lei/forgdit/nco_wcoss2> module load g2/3.5.1
> hang.lei@clogin03:/lfs/h2/emc/eib/save/hang.lei/forgdit/nco_wcoss2> module load g2tmpl/1.13.0
> 
> The source code for g2/3.5.1 is in : /lfs/h2/emc/eib/save/hang.lei/forgdit/nco_wcoss2/pkg/g2-v3.5.1
> 
> Thanks,
> Hang 
> 
> On Wed, Jul 17, 2024 at 9:10 AM Andrew Benjamin - NOAA Federal <[andrew.benjamin@noaa.gov](mailto:andrew.benjamin@noaa.gov)> wrote:
> Hi all,
> 
> Ed, were you or anyone from your team able to find or recreate Wen's issue?
> 
> Andrew 
> 
> On Thu, Jul 11, 2024 at 2:35 PM Wen Meng - NOAA Federal <[wen.meng@noaa.gov](mailto:wen.meng@noaa.gov)> wrote:
> I assume you would like look the UPP code
> https://github.com/NOAA-EMC/UPP/blob/develop/sorc/ncep_post.fd/grib2_module.f
> 
> Wen
> 
> On Thu, Jul 11, 2024 at 2:27 PM Edward Hartnett - NOAA Affiliate <[edward.hartnett@noaa.gov](mailto:edward.hartnett@noaa.gov)> wrote:
> Well yes we do, but the only thing the g2 library does is serve up the 4.49 info. It does not construct the message.
> 
> Can you tell me where the code is in UPP that is constructing the message?
> 
> Thanks,
> Ed
> 
> On Thu, Jul 11, 2024 at 12:19 PM Wen Meng - NOAA Federal <[wen.meng@noaa.gov](mailto:wen.meng@noaa.gov)> wrote:
> Andrew and Edward,
> 
> Do you have the g2tmpl standalone test for validating [temp 4.49](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp4-49.shtml)? 
> 
> Thanks,
> 
> Wen
> 
> On Thu, Jul 11, 2024 at 2:12 PM Wen Meng - NOAA Federal <[wen.meng@noaa.gov](mailto:wen.meng@noaa.gov)> wrote:
> Hi Li,
> 
> I conducted the UPP testing on Dogwood with g2/3.5.1 and g2tmpl/1.13.0 installed by Hang at
> /lfs/h2/emc/eib/save/Hang.Lei/forgdit/nco_wcoss2/install/modulefiles/compiler/intel/19.1.3.304. My test was completed at /u/wen.meng/ptmp/post_gefs_2018081600. Somehow the grib2 file generated has an issue:
> ==================
> wen.meng@dlogin01 post_gefs_2018081600$ wgrib2 GFSPRS.GrbF18
> 1:0:d=2018081600:PRMSL:mean sea level:18 hour fcst:ENS=+7
> 2:1453687:d=2018081600:PRES:1 hybrid level:18 hour fcst:ENS=+7
> 3:2571796:d=2018081600:HGT:1 hybrid level:18 hour fcst:ENS=+7
> 4:2984213:d=2018081600:TMP:1 hybrid level:18 hour fcst:ENS=+7
> 5:3231516:d=2018081600:RH:1 hybrid level:18 hour fcst:ENS=+7
> 6:4700088:d=2018081600:UGRD:1 hybrid level:18 hour fcst:ENS=+7
> 7:5768607:d=2018081600:VGRD:1 hybrid level:18 hour fcst:ENS=+7
> 
> *** FATAL ERROR: rd_grib2_msg_seq_file, missing end section ('7777') ***
> =====================
> 
> Could you do the UPP testing from your end to see if you get the same problem as my testing?
> 
> Thanks,
> 
> Wen

**Comment by edwardhartnett** [comment]
Hang says:

```
Upon my check with NCO :
The RFC has been moved again due to CWD.  It's on the calendar now for Monday, August 12th. 
```

**Comment by AndrewBenjamin-NOAA** [comment]
Thank you for the update

**Comment by Hang-Lei-NOAA** [comment]
Yes, due to a series of wcoss2 maintenance issues. All RFCs delayed
recently.

**Comment by WenMeng-NOAA** [comment]
@Hang-Lei-NOAA Have g2 and g2tmpl installations been scheduled for today?

**Comment by WenMeng-NOAA** [comment]
I saw the official g2/3.5.1 and g2tmpl/1.13.0 are available on WCOSS2.

**Comment by Hang-Lei-NOAA** [comment]
Great! Thanks for letting us know.
So, NCO implemented them.

**Comment by AndrewBenjamin-NOAA** [comment]
I see the updates on cactus (dev), but not on dogwood (prod). But we are in Enhanced Caution today so they probably won't make it to prod until that expires.

**Comment by WenMeng-NOAA** [comment]
The g2/3.5.1 and g2tmpl/1.13.0 have been successfully installed on WCOSS2, and UPP has been updated with these new libraries. You may close this issue as completed. Thanks!
