### ISSUE TITLE
Install ip v5.0.0

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/WCOSS2-requests#9]
The new ip library version acquired the all sp functionallity, rendering the latter obsolete.  It would be convenient for multiple repositories to have ip v5.0.0 installed on all platforms so that CMake recipes can be updated to exclude sp.

**Comment by Hang-Lei-NOAA** [comment]
@DavidHuber-NOAA The ip/5.0.0 has been installed on acorn for preparation testing. Please load and test:
module use /lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/modulefiles/compiler/intel/19.1.3.304
module load ip/5.0.0

**Comment by DavidHuber-NOAA** [comment]
Thank you @Hang-Lei-NOAA.  Unfortunately, I do not have a good way to test this installation on Acorn.  The GSI, UFS_Utils, and GSI-utils all use this library, but they are not currently ported to Acorn and I'm not sure how extensively these applications would test the library.

@edwardhartnett @AlexanderRichert-NOAA Could you point me to a test (tests) to verify that the IP library is working correctly?

**Comment by Hang-Lei-NOAA** [comment]
@David Our unit test cannot guarantee its working in the model. Therefore,
modeling test is the necessary step for verification.

**Comment by AlexanderRichert-NOAA** [comment]
@DavidHuber-NOAA would you be able to use the stack-stack 1.7.0 or 1.8.0 installations on Acorn to test? Both have ip 5.0.

**Comment by DavidHuber-NOAA** [comment]
Alright, I will try getting the GSI on Acorn.  Working with the spack-stack installation there should make that effort much easier.

**Comment by DavidHuber-NOAA** [comment]
@AlexanderRichert-NOAA I do not see a module file for crtm under `/lfs/h1/emc/nceplibs/noscrub/spack-stack/spack-stack-1.8.0/envs/ue-intel-19.1.3.304/install/modulefiles/intel/19.1.3.304`.  Am I looking in the right place?

**Comment by DavidHuber-NOAA** [comment]
Ah, disregard.  I see I should be looking in the mpich suite of modules.

**Comment by edwardhartnett** [comment]
@DavidHuber-NOAA did you get to ip-5.0.0 and did it work for you?

**Comment by DavidHuber-NOAA** [comment]
@edwardhartnett I need to finish porting/testing the GSI on Acorn first, then I can test this installation.  I hope to finish with all of that by the end of the week.

**Comment by DavidHuber-NOAA** [comment]
Opened GSI port to Acorn PR https://github.com/NOAA-EMC/GSI/pull/793.

**Comment by DavidHuber-NOAA** [comment]
I have been on sick leave the latter half of the week, so I won’t get to this today.  I’ll try again next week.

Briefly: initial results show differences between ip 2.3.3 and 5.0 in (IIRC) the RRFS regression test.

**Comment by DavidHuber-NOAA** [comment]
@Hang-Lei-NOAA As a prerequisite to porting the GSI to Acorn, I will also need CRTM v2.4.0.1 installed there.  This version is already installed on Cactus and Dogwood, so I would only need the Acorn install.  Should I open another request for that?

**Comment by Hang-Lei-NOAA** [comment]
All software installed on cactus must have been installed on acorn already.
No test no delivery.
@David Huber - NOAA Affiliate ***@***.***> please remember that
/lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/modulefiles is our
EMC maintained library structure on acorn, It should contain the largest
available sets for EMC use.

Please check out
module
use /lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/modulefiles/compiler/intel/19.1.3.304
module load crtm/2.4.0.1

**Comment by DavidHuber-NOAA** [comment]
Ah, very good.  Thanks for the reminder @Hang-Lei-NOAA.

**Comment by DavidHuber-NOAA** [comment]
@Hang-Lei-NOAA I tested IP v5.0.0 within the GSI and all results are identical to IP v3.3.3/SP v2.3.3, so I think we are good to go.

**Comment by Hang-Lei-NOAA** [comment]
Okay, I will go ahead to process it.

**Comment by edwardhartnett** [comment]
Has this been submitted to NCO?

**Comment by Hang-Lei-NOAA** [comment]
Not yet, any other issues on this?

**Comment by Hang-Lei-NOAA** [comment]
The R2O delivery instruction is :
https://docs.google.com/document/d/1Fl_lmsqkbpRnRGlfJCgONYYAsKQK-EcBeLz097DK_pE/edit?usp=sharing

**Comment by edwardhartnett** [comment]
Any progress on this issue?

**Comment by Hang-Lei-NOAA** [comment]
It’s still on NCO’s waiting list for installation.

**Comment by Hang-Lei-NOAA** [comment]
@DavidHuber-NOAA NCO has installed this version on dogwoods. Please test it:
module use /apps/ops/para/libs/modulefiles/compiler/intel/19.1.3.304
module show ip/5.0.0

**Comment by DavidHuber-NOAA** [comment]
@Hang-Lei-NOAA Thanks for the info.  I am able to load the module, but the `ip` library does not seem to be installed in the correct location.  The following environmental variables are set after loading /apps/ops/para/libs/modulefiles/compiler/intel/19.1.3.304/ip/5.0.0.lua:

```console
ip_ROOT=/apps/ops/prod/libs/intel/19.1.3.304/ip/5.0.0
PWD=/lfs/h2/emc/global/noscrub/David.Huber/GSI/gsi_ip_bufr/ush
IP_INC4=/apps/ops/prod/libs/intel/19.1.3.304/ip/5.0.0/include_4
IP_INC8=/apps/ops/prod/libs/intel/19.1.3.304/ip/5.0.0/include_8
IP_INCd=/apps/ops/prod/libs/intel/19.1.3.304/ip/5.0.0/include_d
IP_LIB8=/apps/ops/prod/libs/intel/19.1.3.304/ip/5.0.0/lib64/libip_8.a
IP_LIB4=/apps/ops/prod/libs/intel/19.1.3.304/ip/5.0.0/lib64/libip_4.a
IP_LIBd=/apps/ops/prod/libs/intel/19.1.3.304/ip/5.0.0/lib64/libip_d.a
```
But the directory `/apps/ops/prod/libs/intel/19.1.3.304/ip/5.0.0` does not exist.  Here are the modules loaded at the time of checking this:

```
  1) craype-x86-rome (H)   2) libfabric/1.11.0.0. (H)   3) craype-network-ofi (H)   4) envvar/1.0   5) PrgEnv-intel/8.3.3   6) intel/19.1.3.304   7) craype/2.7.17   8) ip/5.0.0
```

**Comment by Hang-Lei-NOAA** [comment]
@David Huber - NOAA Affiliate ***@***.***>
The NCO require us to test based on their suggested method:
===========================
If the variable $HPC_OPT is set to /apps/ops/*prob*/libs, the module will
point you to "/apps/ops/prod/libs/intel/19.1.3.304/ip/5.0.0". I installed
the libraries in "/apps/ops/para/libs" for your review, so "/apps/ops/*para*
/libs/intel/19.1.3.304/ip/5.0.0" is populated on both machines.  In my
environment, the HPC_OPT variable is set by module "envvar/1.0", but yours
may be set elsewhere.  Please let me know if using "export
HPC_OPT=/apps/ops/para/libs" corrects the module paths and how
testing goes.  I can submit the RFC tomorrow if all goes well.
============================
Could you please try this method?
Or
I have copied their modulefiles and set direct paths
==================my suggested method======================
module use /lfs/h2/emc/eib/save/Hang.Lei/nco
module load ip/5.0.0
module load bufr/12.1.0
====================================

**Comment by DavidHuber-NOAA** [comment]
Thanks for forwarding this info, Hang.  First, I tried testing following NCO's suggested method:

```console
> module purge
> module reset
> module list

Currently Loaded Modules:
  1) craype-x86-rome (H)   2) libfabric/1.11.0.0. (H)   3) craype-network-ofi (H)   4) envvar/1.0

  Where:
   H:  Hidden Module


> echo $HPC_OPT
/apps/ops/prod/libs
```

So it seems that `HPC_OPT` is not set to `/apps/ops/para/libs` when `envvar/1.0` is loaded.  However, manually setting `HPC_OPT` does allow the module files to point to the correct location:
```console
> module unload envvar
> export HPC_OPT=/apps/ops/para/libs
>  module use /apps/ops/para/libs/modulefiles/compiler/intel/19.1.3.304
> module load ip/5.0.0
> module load bufr/12.1.0
> which debufr
/apps/ops/para/libs/intel/19.1.3.304/bufr/12.1.0/bin/debufr
```

Is there another `envvar` module that I am unaware of that sets `HPC_OPT`?

While that is being answered, I will test the GSI against these versions of IP and BUFR.

**Comment by DavidHuber-NOAA** [comment]
~Unfortunately, I cannot test the GSI with this configuration.  The `sp` library requires `HPC_OPT=/apps/ops/prod/libs`.~

~@Hang-Lei-NOAA I will use your custom modules for IP and BUFR so that I do not need to change the value of `HPC_OPT`.~

**Comment by DavidHuber-NOAA** [comment]
Disregard.  I forgot that I had removed the sp module as ip/5.0.0 takes on sp functionality.  I will continue testing with NCO's modules.

**Comment by Hang-Lei-NOAA** [comment]
@David Huber - NOAA Affiliate ***@***.***> Thanks, You did a
great job.

**Comment by DavidHuber-NOAA** [comment]
@Hang-Lei-NOAA I have finished testing ~BUFR 12.1.0~ IP 5.0.0 on Dogwood and the library is performing as expected.  Thanks!!

If we can get that library installed to `/apps/ops/prod/libs` or if NCO can provide a different `envvar` module, then I think we are good to go here.

**Comment by Hang-Lei-NOAA** [comment]
@David Huber - NOAA Affiliate ***@***.***> Thanks Dave for the
quick test. I will go ahead working with NCO to make sure the prod is good
to go.

**Comment by Hang-Lei-NOAA** [comment]
Done by NCO
